# Generated by Django 4.2.7 on 2023-11-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='atr1',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='table1',
            old_name='atr2',
            new_name='YearMax',
        ),
        migrations.AddField(
            model_name='table1',
            name='Coments',
            field=models.CharField(default='no comments', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table1',
            name='Indicator',
            field=models.CharField(default='no indicator', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table1',
            name='Title',
            field=models.CharField(default='no title', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table1',
            name='User',
            field=models.CharField(default='unknown user', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table1',
            name='YearMin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
